### ISSUE TITLE
Empty scene when loading the lz.vsgt file from the vsgExample sample files

### ISSUE THREAD

**Issue by rhabacker** [geefr/vsgvr#10]
I built vsgvr on Linux with libvsg 0.2.8 and loaded the sample lz.vsgt from the vsgExamples project with:
```
$./example_vr ../vsgExamples/data/models/lz.vsgt
```
and got an empty scene in VR using a HTC Vive.

**Comment by geefr** [comment]
Apologies for the delay, turns out this is an easy one to answer. May be confusing but it's not a bug.
If you look at the very end of lz.vsgt the root MatrixTransform has a translation of [50, 50, 50].

One of the important things in VR development is to configure your space well - At the moment the example is hardcoded
to 1 unit == 1 meter, and directly maps to the OpenVR space (Where [0, 0, 0] is the center of your physical space).

The issue of coordinate spaces is a larger issue, hopefully the OpenXR implementation will handle some of it as a side effect,
as OpenXR has a richer concept of 'space' than OpenVR.

A quick hack to make it display is edit lz.vsgt to `Matrix 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1`, which at least brings
the model down into the VR space:
![image](https://user-images.githubusercontent.com/11091460/168345966-1bf7adc9-f87f-4f6a-b56e-96e6dc3f7958.png)
